# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /project_agent

# Copy the current directory contents into the container at /app
COPY . /project_agent

# Install any needed packages specified in requirements.txt
RUN pip3 install -r requirements.txt


# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD ["streamlit run", "app.py"]
