name: Scheduled Python Task

on:
  schedule:
    # Runs the action every day at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # specify your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # assumes dependencies are listed in requirements.txt

      - name: Run Python script
        run: python your_script.py  # replace with your actual script name
